include(
        "karibu-testing-v10",
        "karibu-testing-v10-groovy",
        "karibu-testing-v10-pro-groovy",
        "karibu-testing-v10-spring",
        "karibu-testing-v10:tests",
        "karibu-testing-v23",
        "karibu-testing-v24",
        "karibu-testing-v23:tests",
        "karibu-testing-v24:testrun-stable-webapp",
        "karibu-testing-v24:testrun-stable-module",
        "karibu-testing-v24:testrun-next-webapp",
        "karibu-testing-v24:testrun-next-module",
)
